M48
; DRILL file {KiCad 7.0.7} date Tue 03 Oct 2023 13:22:20
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-10-03T13:22:20+10:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X74.5Y-38.5
X74.5Y-112.0
X92.5Y-54.5
X92.5Y-107.5
X116.5Y-54.5
X116.5Y-107.5
X122.0Y-38.5
X122.0Y-112.0
T0
M30
